config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  EMAIL_REGEX = /\A[^@\s]+@[^@\s]+\z/
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, length: { minimum: 8 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(allowed_params[:email])

    if UserAuthenticator.new(user).authenticate(allowed_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "You are logged in."
    else
      redirect_to root_path, alert: "Something went wrong trying to log in."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login', notice: "Logout with successfully."
  end


  private
  def allowed_params
    params.require(:user).permit([:email, :password])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authorize

  def index
    @tv_show = TvShow.new(Api.new(current_user).data)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_defaults
    { wrapper_html: { class: "form-group" },
      input_html: { class: "form-control" } }
  end

  def asset(name)
    name if Rails.application.assets.find_asset(name)
  end

  def stylesheet_optional(name, options = {})
    stylesheet_link_tag(name, options) if asset(name)
  end

  def device_stylesheet
    file = "phone"  if browser.device.iphone?
    file = "tablet" if browser.device.tablet?
    file || "pc"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application", media: "all" %>
    <%= stylesheet_optional device_stylesheet, media: "all" %>
    <%= csrf_meta_tags %>
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body id="logged-out">
    <div id="container-fluid">
      <div id="sign-in-container">
        <%= render "shared/notifications" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_notifications.html.erb
<% if notice %>
  <div class="alert alert-success fade in" data-alert="alert">
    <a class="close" data-dismiss='alert' href="#">×</a>
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger fade in" data-alert="alert">
    <a class="close" data-dismiss='alert' href="#">×</a>
    <p><%= alert %></p>
  </div>
<% end %>

app/views/welcome/index.html.erb
Hello!

Your tvshow is <%= @tv_show.name %> and its category <%= @tv_show.category  %>.

<%= link_to "Logout", logout_path %>